[package]
name = "mistql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
lexical = { version = "6.0", features = ["format"] }
pest = "2.0"
pest_derive = "2.0"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
snailquote = "0.3"