name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    defaults:
      run:
        working-directory: ./py
    env:
      TYPEGUARD: 1

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-24.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv Python manager
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.0"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
      - name: Install Python
        run: uv venv -p ${{ matrix.python-version }}
      - name: Install deps
        run: uv pip install -e ".[dev]"
      - name: Test
        run: uv run pytest
      - name: Lint
        run: uv run ruff format --check
      - name: Typecheck
        run: uv run mypy -p mistql
